export default [
  " Cuna Jardín (0 año)",
  "Cuna Jardín (1 año)",
  "Cuna Jardín (2 años)",
  "Inicial Jardín (3 años)",
  "Inicial Jardín (4 años)",
  "Inicial Jardín (5 años)",
  "1er grado  Primaria",
  "2do grado - Primaria",
  "3er grado - Primaria",
  "4to grado - Primaria",
  "5to grado - Primaria",
  "6to grado - Primaria",
  "1er grado - Secundaria",
  "2do grado - Secundaria",
  "3er grado - Secundaria",
  "4to grado - Secundaria",
  "5to grado - Secundaria",
];
